src/components/script-component.ts, src/components/script.ts
Centralize management of scripts in `ScriptComponentElement` instead of `ScriptElement`.
=> Refactor pc-scripts element

README.md, examples/positional-sound.html, examples/sound.html, src/components/sound-component.ts, src/components/sound-slot.ts
* `pc-sound` > `pc-sounds`
* `pc-sound-slot` > `pc-sound`
=> Rename sound elements

examples/screen.html, src/components/screen-component.ts, src/entity.ts, src/index.ts
e.g.:
```html
<pc-entity name="screen">
<pc-screen screen-space></pc-screen>
<pc-entity name="text" position="0,20,0">
<pc-element type="text" asset="arial" text="This is Arial"></pc-element>
</pc-entity>
<pc-entity name="text2" position="0,-20,0">
<pc-element type="text" asset="courier" text="This is Courier"></pc-element>
</pc-entity>
</pc-entity>
```
=> Add pc-screen element

examples/glb.html, examples/physics.html, examples/positional-sound.html, examples/screen.html, examples/shapes.html, examples/sound.html, examples/spinning-cube-umd.html, examples/spinning-cube.html, examples/splat.html, src/components/collision-component.ts, src/utils.ts
=> Add support for linear and angular offset for collision component

examples/index.html, examples/spinning-cube.html
Adds a top-level examples browser app:
Includes 'View Code' button:
=> Add Examples Browser

examples/assets/models/shoe.txt, examples/index.html, examples/positional-sound.html, examples/scripts/material-variants.mjs, examples/shoe-configurator.html, examples/styles.css
Simple demonstration of glTF's material variants extension:
=> Add shoe configurator example

README.md, src/components/sound-component.ts
Adds:
* `distance-model`
* `max-distance`
* `ref-distance`
* `roll-off-factor`
=> Add more sound component attributes

examples/car-configurator.html, examples/screen.html, examples/splat.html, examples/text.html, src/app.ts
Adds:
* `alpha`
* `anitalias`
* `depth`
* `stencil`
Switches `high-resolution` to default to `true`.
=> Add more pc-app attributes

examples/car-configurator.html, examples/scripts/camera-frame.mjs, src/components/script-component.ts
=> Enable post effects in car configurator

examples/css/browser.css, examples/index.html, examples/js/example-loader.mjs, examples/scripts/ui.mjs
Add hamburger button with sliding side panel for narrow screens.
=> New mobile design for Examples Browser

examples/animation.html, examples/scripts/ui.mjs, examples/scripts/vr.mjs
Dynamically load and instantiate XR Input Source models.
=> Support XR input sources

eslint.config.mjs, examples/scripts/camera-controls.mjs, examples/scripts/choose-color.mjs, examples/scripts/grid.mjs, examples/scripts/material-variants.mjs, examples/scripts/orbit.mjs, examples/scripts/planetary-camera.mjs, examples/scripts/planetary-motion.mjs, examples/scripts/shadow-catcher.mjs, examples/scripts/text3d.mjs, examples/scripts/ui.mjs, examples/scripts/video-texture.mjs, examples/scripts/xr-controllers.mjs, package.json
* Enable ESLint for the examples scripts
* Implement proper `destroy` for video texture script
=> Lint example scripts

src/app.ts, src/asset.ts, src/async-element.ts, src/components/camera-component.ts, src/components/collision-component.ts, src/components/component.ts, src/components/element-component.ts, src/components/gsplat-component.ts, src/components/light-component.ts, src/components/listener-component.ts, src/components/render-component.ts, src/components/rigidbody-component.ts, src/components/screen-component.ts, src/components/script-component.ts, src/components/script.ts, src/components/sound-component.ts, src/components/sound-slot.ts, src/entity.ts, src/material.ts, src/model.ts, src/module.ts, src/scene.ts, src/sky.ts
* Enhance class descriptions.
* Hide constructors from the docs (since you should be creating elements in HTML or with `document.createElement` instead).
=> Improve JSDocs

examples/animation.html, examples/scripts/xr-navigation.mjs
Point and select (pinch when using hand tracking) to navigate.
=> Add XR navigation script

src/components/camera-component.ts
Add attributes `gamma` and `tonemap` to `pc-camera`.
=> Expose gamma and tonemap on pc-camera

examples/scripts/ui.mjs
https://github.com/user-attachments/assets/aabcbdec-7d21-41ba-b1bc-a3002e95aacb
A follow up PR will disable skybox rendering where appropriate.
=> Add initial AR support to the examples browser

examples/animation.html, examples/basic-shapes.html, examples/car-configurator.html, examples/glb.html, examples/physics.html, examples/positional-sound.html, examples/scripts/xr-navigation.mjs, examples/shoe-configurator.html, examples/splat.html, examples/text3d.html, examples/video-texture.html
* Reintroduce the `xr-navigation.mjs` script for now with local edits.
* Copy camera's transform into camera root entity on XR session start and restore on exit.
=> Init XR camera's transform correctly

examples/assets/models/fps-map.txt, examples/car-configurator.html, examples/fps-controller.html, examples/js/example-list.mjs, examples/scripts/static-body.mjs, examples/solar-system.html
=> Add FPS Controller example

examples/animation.html, examples/car-configurator.html, examples/fps-controller.html, examples/glb.html, examples/physics.html, examples/positional-sound.html, examples/screen.html, examples/shoe-configurator.html, examples/solar-system.html, examples/sound.html, examples/spinning-cube.html, examples/splat.html, examples/text.html, examples/tween.html, examples/video-texture.html, src/asset.ts
Since the more common usage is to preload assets.
=> Change pc-asset's preload attribute to lazy

examples/assets/scripts/annotation.mjs
* Use injected CSS classes
* Move material creation into a utility function
* Break the update function into sub-functions
* Darken hotspots
=> Annotation script refactor

examples/assets/scripts/shadow-catcher.mjs
=> [FIX] Allow shadow catcher to handle model deletion

examples/assets/scripts/tweener.mjs, examples/video-recorder.html
Switches out the boring spinning grey cube for a splat of me! Generate a video like this now:
https://github.com/user-attachments/assets/6dfa025c-e49c-4ca0-a098-e096daeb364e
=> Add biker splat to video recorder example

examples/assets/scripts/annotation.mjs
Reverts playcanvas/web-components#96
=> Revert "Annotation script refactor"

examples/assets/scripts/shadow-catcher.mjs
Reverts playcanvas/web-components#98
=> Revert "[FIX] Allow shadow catcher to handle model deletion"

examples/assets/scripts/annotation.mjs
Reverts playcanvas/web-components#108
=> Revert "Revert "Annotation script refactor""

src/app.ts
Giving better visuals at the expense of performance feels like a better default and matches the existing docs.
=> Default pc-app to high resolution

examples/assets/scripts/annotation.mjs
=> Add arrows to annotation panels

examples/assets/scripts/choose-color.mjs, examples/assets/scripts/material-variants.mjs, examples/css/example.css, examples/js/example.mjs
Share more button styles from example.css.
=> Refactor example CSS

examples/ar-hand-gestures.html, examples/assets/scripts/hand-gestures.mjs
In progress example using MediaPipe to detect a set of hand gestures (thumbs up, thumbs down, etc) and log them to the JS console. A follow up PR will add some graphical effects.
=> Add AR hand gesture detection example

examples/js/example.mjs
Show/hide AR and VR buttons properly based on XR availability events.
=> More robust handling of XR availability
